name = "kop-lodge-website"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "kop-lodge-platform"
database_id = "7be87ef0-979a-4363-8bed-f04a4a6dd991"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "kop-lodge-media"

[vars]
# Set to your Cloudflare Zero Trust team name
# (the subdomain of .cloudflareaccess.com)
CF_ACCESS_TEAM_NAME = "canvasback"
