name = "kop-lodge-website"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "kop-lodge-platform"
database_id = "7be87ef0-979a-4363-8bed-f04a4a6dd991"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "kop-lodge-media"

[vars]
ADMIN_TOKEN_HASH = "9e78061e6eb11997bba0cd537bda08756d3d5a9480c7ec2f45737ebafc8c34aa"
